[tool.poetry]
name = "wechat-robot"
version = "0.1.0"
description = "机器人软件"
authors = ["yxj52 <1028530975@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
